//
//  DevPreview.swift
//  AirBnbEd
//
//  Created by vbugrym on 25.11.2023.
//

import Foundation

class DevPreview {
    
    static let shared = DevPreview()
    
    private init() { }
    
    let listings: [Listing] = [
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "John Doe",
                                 imageUrl: "profile"),
            bedrooms: 2,
            bathrooms: 1,
            guests: 4,
            beds: 2,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 100,
            latitude: 40.7128,
            longitude: -74.0060,
            address: "123 Main St",
            city: "New York",
            state: "NY",
            title: "Cozy Apartment",
            rating: 4.5,
            features: [.selfCheckIn, .superHost],
            amenities: [.balcony, .kitchen, .laundry],
            type: .apartment
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "Jane Smith",
                                 imageUrl: "profile2"),
            bedrooms: 3,
            bathrooms: 2,
            guests: 6,
            beds: 3,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 150,
            latitude: 34.0522,
            longitude: -118.2437,
            address: "456 Oak St",
            city: "Los Angeles",
            state: "CA",
            title: "Spacious House",
            rating: 4.8,
            features: [.selfCheckIn, .superHost],
            amenities: [.alarmSystem, .pool, .wifi, .office],
            type: .house
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "Bob Johnson",
                                 imageUrl: "profile3"),
            bedrooms: 1,
            bathrooms: 1,
            guests: 2,
            beds: 1,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 80,
            latitude: 37.7749,
            longitude: -122.4194,
            address: "789 Pine St",
            city: "San Francisco",
            state: "CA",
            title: "Charming Studio",
            rating: 4.2,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .tv, .wifi],
            type: .apartment
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "John Doe",
                                 imageUrl: "profile"),
            bedrooms: 4,
            bathrooms: 3,
            guests: 8,
            beds: 4,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 200,
            latitude: 41.8781,
            longitude: -87.6298,
            address: "321 Maple St",
            city: "Chicago",
            state: "IL",
            title: "Luxury Penthouse",
            rating: 4.9,
            features: [.selfCheckIn, .superHost],
            amenities: [.balcony, .kitchen, .pool, .wifi],
            type: .house
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "Jane Smith",
                                 imageUrl: "profile2"),
            bedrooms: 2,
            bathrooms: 2,
            guests: 5,
            beds: 3,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 120,
            latitude: 33.4484,
            longitude: -112.0740,
            address: "555 Rose St",
            city: "Phoenix",
            state: "AZ",
            title: "Modern Townhouse",
            rating: 4.7,
            features: [.selfCheckIn, .superHost],
            amenities: [.balcony, .pool, .wifi, .kitchen, .laundry],
            type: .townHouse
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "Bob Johnson",
                                 imageUrl: "profile3"),
            bedrooms: 3,
            bathrooms: 2,
            guests: 6,
            beds: 3,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 160,
            latitude: 37.3382,
            longitude: -121.8863,
            address: "987 Elm St",
            city: "San Jose",
            state: "CA",
            title: "Contemporary House",
            rating: 4.6,
            features: [.selfCheckIn, .superHost],
            amenities: [.pool, .tv, .wifi],
            type: .house
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "John Doe",
                                 imageUrl: "profile"),
            bedrooms: 1,
            bathrooms: 1,
            guests: 2,
            beds: 1,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 90,
            latitude: 36.7783,
            longitude: -119.4179,
            address: "654 Cedar St",
            city: "Fresno",
            state: "CA",
            title: "Studio with a View",
            rating: 4.4,
            features: [.selfCheckIn, .superHost],
            amenities: [.laundry, .wifi],
            type: .apartment
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "Jane Smith",
                                 imageUrl: "profile2"),
            bedrooms: 2,
            bathrooms: 2,
            guests: 4,
            beds: 2,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 110,
            latitude: 32.7157,
            longitude: -117.1611,
            address: "789 Oak St",
            city: "San Diego",
            state: "CA",
            title: "Beachfront Condo",
            rating: 4.3,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .tv, .wifi, .alarmSystem],
            type: .apartment
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "Bob Johnson",
                                 imageUrl: "profile3"),
            bedrooms: 3,
            bathrooms: 2,
            guests: 6,
            beds: 3,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 170,
            latitude: 39.9526,
            longitude: -75.1652,
            address: "876 Walnut St",
            city: "Philadelphia",
            state: "PA",
            title: "Historic Townhome",
            rating: 4.7,
            features: [.selfCheckIn, .superHost],
            amenities: [.pool, .balcony, .kitchen, .laundry, .wifi],
            type: .townHouse
        ),
        Listing(
            id: UUID().uuidString,
            owner: Listing.Owner(id: UUID().uuidString,
                                 name: "John Doe",
                                 imageUrl: "profile"),
            bedrooms: 4,
            bathrooms: 3,
            guests: 8,
            beds: 4,
            imageURLs: ["image-1", "image-2", "image-3", "image-4"],
            pricePerNight: 190,
            latitude: 42.3601,
            longitude: -71.0589,
            address: "543 Maple St",
            city: "Boston",
            state: "MA",
            title: "Classic Brownstone",
            rating: 4.9,
            features: [.selfCheckIn, .superHost],
            amenities: [.laundry, .balcony, .wifi, .pool],
            type: .villa
        ),
    ]
}
