//
//  DevPreview.swift
//  AirBnbEd
//
//  Created by vbugrym on 25.11.2023.
//

import Foundation

class DevPreview {
    var listings: [Listing] = [
        .init(id: UUID().uuidString,
              owner: Listing.Owner(id: UUID().uuidString,
                                  name: "Mike Wasowsky",
                                  imageUrl: "profile"),
              bedrooms: 1, 
              bathrooms: 2,
              guests: 4,
              beds: 2,
              imageURLs: ["image-1", "image-2", "image-3", "image-4"],
              pricePerNight: 150,
              latitude: 25.1234,
              longitude: -50.3462,
              address: "13th Avenue",
              city: "New Jersey",
              state: "New York",
              title: "Jersey House",
              rating: 4.78,
              features: [.selfCheckIn, .superHost],
              amenities: [.kitchen, .laundry, .tv, .wifi], 
              type: .house),
        .init(id: UUID().uuidString,
              owner: Listing.Owner(id: UUID().uuidString,
                                  name: "Mike Wasowsky",
                                  imageUrl: "profile"),
              bedrooms: 1,
              bathrooms: 1,
              guests: 2,
              beds: 1,
              imageURLs: ["image-1", "image-2", "image-3", "image-4"],
              pricePerNight: 100,
              latitude: 25.1204,
              longitude: -49.1045,
              address: "134 Main St",
              city: "New Wooper",
              state: "New York",
              title: "Wooper Apartment",
              rating: 4.98,
              features: [.selfCheckIn, .superHost],
              amenities: [.kitchen, .laundry, .tv, .wifi], 
              type: .apartment),
        .init(id: UUID().uuidString,
              owner: Listing.Owner(id: UUID().uuidString,
                                  name: "John Deer",
                                  imageUrl: "profile"),
              bedrooms: 2,
              bathrooms: 3,
              guests: 5,
              beds: 3,
              imageURLs: ["image-1", "image-2", "image-3", "image-4"],
              pricePerNight: 250,
              latitude: 15.1234,
              longitude: -20.3462,
              address: "Mapel St",
              city: "New Orlean",
              state: "Washington",
              title: "Super Cozy Villa",
              rating: 5.00,
              features: [.selfCheckIn, .superHost],
              amenities: [.kitchen, .laundry, .tv, .wifi, .balcony, .alarmSystem],
              type: .villa),
        .init(id: UUID().uuidString,
              owner: Listing.Owner(id: UUID().uuidString,
                                  name: "Bill Moorey",
                                  imageUrl: "profile"),
              bedrooms: 1,
              bathrooms: 1,
              guests: 2,
              beds: 1,
              imageURLs: ["image-1", "image-2", "image-3", "image-4"],
              pricePerNight: 66,
              latitude: 15.1234,
              longitude: -10.3462,
              address: "24th Road",
              city: "Salt Lake City",
              state: "Utah",
              title: "Billy's Rancho",
              rating: 4.78,
              features: [.selfCheckIn, .superHost],
              amenities: [.kitchen, .laundry, .tv, .wifi], 
              type: .house),
        .init(id: UUID().uuidString,
              owner: Listing.Owner(id: UUID().uuidString,
                                  name: "Mike Peers",
                                  imageUrl: "profile"),
              bedrooms: 5,
              bathrooms: 5,
              guests: 12,
              beds: 6,
              imageURLs: ["image-1", "image-2", "image-3", "image-4"],
              pricePerNight: 550,
              latitude: 40.1234,
              longitude: -40.3462,
              address: "Barn St",
              city: "Moon",
              state: "Texas",
              title: "Peer's Family Mansion",
              rating: 4.78,
              features: [.selfCheckIn, .superHost],
              amenities: [.kitchen, .laundry, .tv, .wifi], 
              type: .townHouse)
    ]
}
